/**
 * 
 */
package grammar.input.xml;

public enum ParseMode {
	OFF,
	MATCH_TYPE,
	RULE, NAME, SUMMARY,
	STEM, INFIX, SUFFIX, SEGMENT,
	PARENT,
	PATTERN,
	GENDER, MULTIPLICITY, PERSON,
	TENSE, MOOD, AUXILIARY, COMPOSITE, AUXILIARY_OF, SEQUENCE, CLASSIFICATION,
	NOUN_CLASS, ABBREVIATION;
}